pricewise/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf import settings
from  django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home, name='home'),
    path('under-construction/',views.under_construction, name='under_construction'),
    path('accounts/',include('authentication.urls')),
    path('products/',include('products.urls')),
    path('watchlist/',include('watchlist.urls')),
    path('tracking/',include('tracking.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_URL)

products/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name='products'

urlpatterns = [
    path('search/', views.search_products, name='search_products'),
    path('view/<str:product_id>/', views.view_product, name='view_product'),
    path('add/', views.add_product, name='add_product'),
    path('all/', views.all_products, name='all_products'),
    path('tracked/', views.tracked_items, name='tracked_items'),
]

watchlist/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name='watchlist'

urlpatterns = [
    path('create/', views.create_watchlist, name='create_watchlist'),
    path('all/', views.all_watchlists, name='all_watchlists'),
    path('add/', views.add_to_watchlist, name='add_to_watchlist'),
    path('view/<str:watchlist_id>/', views.view_watchlist, name='view_watchlist'),
    path('remove_item/', views.remove_item, name='remove_item'),
    path('remove/', views.remove_watchlist, name='remove_watchlist'),
]

watchlist/models.py
from django.db import models
from django.conf import settings
from products.models import Product
import uuid

# Create your models here.

class WatchList(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    name=models.CharField(max_length=255,blank= True)
    watchlist_id=models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, unique=True)
    
    def save(self,*args,**kwargs):
        if not self.name:
            self.name=f"{self.user.username}'s watchlist"
        super().save(*args,**kwargs)

    def __str__(self):
        return f"{self.user.username}'s Watchlist"

class WatchListItem(models.Model):
    watchlist=models.ForeignKey(WatchList, on_delete=models.CASCADE, related_name='items')
    product=models.ForeignKey(Product, on_delete=models.CASCADE)
    class Meta:
        unique_together=('watchlist','product')

    def __str__(self):
        return f"{self.watchlist.user.username}- {self.product.name}"

watchlist/views.py
from django.shortcuts import render,redirect, get_object_or_404
from django.urls import reverse
from .models import WatchList, WatchListItem
from products.models import Product
from django.contrib import messages
from django.contrib.auth.decorators import login_required

# Create your views here.
@login_required
def create_watchlist(request):
    if request.method=='POST':
        name=request.POST.get('name')
        watchlist = WatchList(user=request.user, name=name)
        watchlist.save()
        messages.success(request, 'Watchlist created successfully!')
        return redirect(reverse('home'))
    return render(request, 'watchlist/create_watchlist.html')

@login_required
def add_to_watchlist(request):
    if request.method=='POST':
        product_id=request.POST.get('product_id')
        product=get_object_or_404(Product, product_id=product_id)
        watchlist_id=request.POST.get('watchlist_id')
        watchlist=get_object_or_404(WatchList, watchlist_id=watchlist_id)
        try:
            if product:
                watchlist_item=WatchListItem(watchlist=watchlist, product=product)
                watchlist_item.save()
                messages.success(request, 'Product added to watchlist successfully.')
        except Exception as e:
            messages.error(request, f'{e} An error occured while adding the product.')
            return redirect('watchlist:view_watchlist', watchlist_id=watchlist_id)
    return redirect('products:view_product', product=product)

@login_required
def all_watchlists(request):
    watchlists= WatchList.objects.all()
    return render(request, 'watchlist/all_watchlists.html', {'watchlists': watchlists})

@login_required
def view_watchlist(request,watchlist_id):
    watchlist=get_object_or_404(WatchList, watchlist_id=watchlist_id)
    watchlist_items=watchlist.items.all()
    watchlists= WatchList.objects.all()
    return render(request, 'watchlist/view_watchlist.html', {'watchlist': watchlist, 'watchlist_items':watchlist_items, 'watchlists':watchlists})

@login_required
def remove_item(request):
    product_id=request.POST.get('item_id')
    watchlist_item = get_object_or_404(WatchListItem, product_id=product_id)
    watchlist_id = watchlist_item.watchlist_id
    try:
        watchlist_item.delete()
        messages.success(request, 'Item removed from watchlist successfully.')
    except Exception as e:
        messages.error(request, f"Failed to remove item. {e}")
    return redirect('watchlist:view_watchlist', watchlist_id=watchlist_id)

@login_required
def remove_watchlist(request):
    watchlist_id=request.POST.get('watchlist_id')
    watchlist = get_object_or_404(WatchList, watchlist_id=watchlist_id)
    try:
        watchlist.delete()
        messages.success(request, 'Watchlist removed from watchlist successfully.')
    except Exception as e:
        messages.error(request, f"Failed to remove watchlist. {e}")
    return redirect('watchlist:all_watchlists')

templates/watchlist/all_watchlists.html
{% extends "pricewise/home.html" %}
{% block style %}
<head>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0&icon_names=delete" />
</head>
<style>
    .watchlist-container{
        padding: 20px;
        width: 800px;
        margin:0 auto;
    }
    .watchlist-header {
        display: flex;
        align-items: center;
        justify-content: space-between;
        margin-bottom: 20px;
    }
    .watchlist-header h2 {
        margin: 0;
    }
    .watchlist-header hr {
        flex-grow: 1;
        margin: 0 10px;
        border: 0;
        border-top: 1px solid #ffffff;
    }
    .watchlist-buttons {
        display: flex;
        gap: 10px;
        margin-bottom: 20px;
    }
    .watchlist-button {
        background-color: #fff;
        border:1px solid rgba(0,0,0,0.1);
        border-radius: 20px;
        padding: 6px 15px;
        text-align: center;
        cursor: pointer;
    }
    .watchlist-button:hover {
        background-color: #f9f9f9;
        border-color: #333;
    }
    .watchlist-button.active {
        border-color: #333;
    }
    .watchlist-button i {
        display: block;
        font-size: 24px;
        margin-bottom: 5px;
    }
    .holder{
        display: flex;
        justify-content: space-between;
        align-items: center;
        border-top: 1px solid #ddd;
        border-bottom: 1px solid #ddd;        
    }
    form{
        display:contents;
    }
    .watchlist-table{
        width: 100%;
        border-collapse: collapse;
        margin-top: 20px;
    }
    th, td {
        padding: 10px;
        border-bottom: 1px solid #ddd;
    }
    th {
        text-align: left;
    }
    .status.expensive {
        color: red;
    }
    .status.affordable {
        color: green;
    }
    .material-symbols-outlined{
        color:#999;
    }
    .dlt-button{
        background: none;
        border: none;
        cursor: pointer;
    }
    .item-row:hover{
        background-color: #f9f9f9;

    }
    .remove_item{
        text-align: end;
    }
    
</style>
{% endblock style %}
{% block content %}
<div class="watchlist-container" style="padding: 20px; width: 800px;margin:0 auto;">
    <div class="watchlist-header">
        <h2>Your Watchlists</h2>
        <hr>
    </div>
    <div class="watchlist-buttons">
        <button class="watchlist-button" onclick="event.stopPropagation(); location.href='{% url "watchlist:create_watchlist" %}'">+ Create Watchlist</button>
        {% if watchlists %}
        {% for watchlist in watchlists %}
            <button class="watchlist-button" onclick="event.stopPropagation(); location.href='{% url "watchlist:view_watchlist" watchlist.watchlist_id %}'">{{watchlist.name}} </button>
        {% endfor %}
        {% endif %}
        <button class="watchlist-button" onclick="event.stopPropagation(); location.href='{% url "products:tracked_items" %}'">Tracked items</button>
    </div>
    {% block table %}{% endblock table %}
</div>
{% endblock content %}





























{% comment %} {% if watchlists %}
    {% for watchlist in watchlists %}
    <div>
        <li style="display:flex; justify-content:space-between; border: 1px solid #ddd; padding: 20px; margin: 20px 50px; border-radius: 5px; box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);" onclick="location.href='{% url 'products:view_watchlist' watchlist.watchlist_id %}'">
            <span>{{ watchlist.name }}</span>
            <form method='post' action="{% url "products:remove_watchlist" %}">
                {% csrf_token %}
                <input type="hidden" name="watchlist_id" value='{{ watchlist.watchlist_id }}'>
                <button type="submit" onclick="event.stopPropagation()">Remove</button>
            </form>
        </li>
    </div>
    {% endfor %}
{% else %}
<p style="color:red;">No Watchlists</p>
<button onclick="event.stopPropagation(); location.href='{% url "products:create_watchlist" %}'">Create Watchlist</button>
{% endif %}
{% endblock content %} {% endcomment %}

templates/watchlist/create_watchlist.html
{% extends "pricewise/home.html" %}
{% block content %}
    <form method="post">
        {% csrf_token %}
        <label for="name">Watchlist Name</label><br>
        <input type="text" id="name" name="name" required>
        <button type="submit">Create Watchlist</button>
    </form>
{% endblock content %}

templates/watchlist/view_watchlist.html
{%extends 'watchlist/all_watchlists.html'%}
{% block table %}
{% if watchlist_items %}
<div class='holder'>
    <h2>{{watchlist.name}}</h2>
    <form action="{% url "watchlist:remove_watchlist" %}">
    {% csrf_token %}
    <input type="hidden" name="watchlist_id" value="{{watchlist.watchlist_id}}">
    <button class="dlt-button" onclick="event.stopPropagation();"><span class="material-symbols-outlined">delete</span></button>
    </form>
</div>
<table style="width: 100%;border-collapse: collapse;margin-top: 20px;">
    <tr>
        <th>Item</th>
        <th>Price</th>
        <th>Status</th>
        <th></th>
    </tr>
    {% for item in watchlist_items %}
    <tr class='item-row'>
        <td>{{item.product.name}}</td>
        <td class="price">₹{{item.product.current_price}}</td>
        <td class="status {{item.product_alert.status}}">{{item.product_alert.status}}</td>
        <td class='remove_item'><form method='post' action="{% url "watchlist:remove_item" %}">
            {% csrf_token %}
            <input type="hidden" name="item_id" value="{{ item.product.product_id }}">
            <button class="dlt-button" onclick="event.stopPropagation();"><span class="material-symbols-outlined">delete</span></button>
        </form></td>
    </tr>
    {% endfor %}
</table>
{% else %}
<p style="color:red;">"Watchlist is empty."</p>
<button onclick="event.stopPropagation(); location.href='{% url "products:all_products" %}'">Add items</button>
{% endif %}



















{% comment %} <h2>{{watchlist.name}}</h2>
    {% if watchlist_items %}
        {% for item in watchlist_items %}
        <li style="display:flex; justify-content:space-between; border: 1px solid #ddd; padding: 20px; margin: 20px 50px; border-radius: 5px; box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);"  onclick="location.href='{% url 'products:view_product' item.product.product_id %}'">
            <span>{{ item.product.name }} - ₹{{ item.product.current_price }}</span>
            <form method='post' action="{% url "products:remove_item" %}">
                {% csrf_token %}
                <input type="hidden" name="item_id" value="{{ item.product.product_id }}">
                <button onclick="event.stopPropagation();">Remove</button>
            </form>
        </li>
        {% endfor %}
    {% else %}
        <p style="color:red;">"Watchlist is empty."</p>
        <button onclick="event.stopPropagation(); location.href='{% url "products:all_products" %}'">Add items</button>
    {% endif %} {% endcomment %}
{% endblock table %}