authentication/urls.py
from django.urls import path
from .views import register_view, login_view, logout_view, user_list_view

app_name = 'accounts'

urlpatterns = [
    path('register/', register_view, name='register'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('users/', user_list_view, name='user_list'),
]

pricewise/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf import settings
from  django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home, name='home'),
    path('under-construction/',views.under_construction, name='under_construction'),
    path('accounts/',include('authentication.urls')),
    path('products/',include('products.urls')),
    path('watchlist/',include('watchlist.urls')),
    path('tracking/',include('tracking.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_URL)

products/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name='products'

urlpatterns = [
    path('search/', views.search_products, name='search_products'),
    path('view/<str:product_id>/', views.view_product, name='view_product'),
    path('add/', views.add_product, name='add_product'),
    path('all/', views.all_products, name='all_products'),
    path('tracked/', views.tracked_items, name='tracked_items'),
]

tracking/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name='tracking'

urlpatterns = [
    path('track-product/<str:id>', views.track_product, name='track_product'),
    path('product-list/', views.product_list, name='product_list'),
    path('send-email/', views.send_email, name='send_email'),
]

watchlist/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name='watchlist'

urlpatterns = [
    path('create/', views.create_watchlist, name='create_watchlist'),
    path('all/', views.all_watchlists, name='all_watchlists'),
    path('add/', views.add_to_watchlist, name='add_to_watchlist'),
    path('view/<str:watchlist_id>/', views.view_watchlist, name='view_watchlist'),
    path('remove_item/', views.remove_item, name='remove_item'),
    path('remove/', views.remove_watchlist, name='remove_watchlist'),
]

pricewise/views.py
from django.shortcuts import render
# Create your views here.

def home(request):
    return render(request, 'pricewise/home.html')

def under_construction(request):
    return render(request, 'pricewise/under-construction.html')

templates/pricewise/home.html
<html>
<head>
    <title>PriceWise</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Geist:wght@100..900&family=Raleway:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0" />
    <style>
        body {
            font-family: 'Geist', serif;
            margin: 0;
            padding: 0;
            box-sizing: border-box;
            color:#333;
        }
        a{
            text-decoration:none;
            color:inherit;
        }
        .container {
            max-width: 1200px;
            margin: 0 auto;
            padding: 20px;
        }
        header {
            text-align: center;
            padding: 20px 0;
        }
        header h1 {
            font-size: 5.5em;
            margin: 0;
        }
        header p {
            color: #666;
            margin: 10px 0 20px;
        }
        nav {
            display: flex;
            align-items: center;
            justify-content: space-between;
            padding: 16px 0;
            margin: 0 16px;
            border-bottom: 1px solid #ddd;
        }
        nav h3 {
            font-size:1.6em;
            margin:0;
        }
        .nav-links {
            flex-grow: 0.1;
            display: flex;
            justify-content: space-between;
            align-items: center;
            list-style: none;
            margin: 0;
        }
        .nav-links a {
            text-decoration: none;
            color: #333;
        }
        .nav-links p {
            font-size: 1.2em;
            margin: 0;
        }
        .nav-links button {
            padding: 10px 20px;
            border: none;
            background-color: #333;
            color: #fff;
            border-radius: 4px;
            cursor: pointer;
        }
        .nav-links button:hover {
            background-color: #555;
        }
        .hamburger {
            display: none;
            cursor: pointer;
        }
        .hamburger div {
            width: 25px;
            height: 3px;
            background-color: #333;
            margin: 5px;
            transition: all 0.3s ease;
        }
        @media (max-width: 768px) {
            nav {
                flex-direction: column;
                align-items: flex-start;
            }
            .nav-links {
                flex-direction: column;
                width: 100%;
                display: none;
            }
            .nav-links li {
                width: 100%;
                text-align: center;
                margin: 10px 0;
            }
            .nav-links.active {
                display: flex;
            }
            .hamburger {
                display: block;
            }
        }
        .search-bar {
            display: flex;
            justify-content: center;
            margin-bottom: 40px;
        }
        .search-bar input {
            width: 300px;
            padding: 10px;
            border: 1px solid #ddd;
            border-radius: 4px 0 0 4px;
        }
        .search-bar button {
            padding: 10px 20px;
            border: none;
            background-color: #333;
            color: #fff;
            border-radius: 0 4px 4px 0;
            cursor: pointer;
        }
        footer {
            bottom: 0;
            width:100%;
            text-align: center;
        }
        footer p {
            margin: 5px 0;
        }
        footer a {
            color: #000;
            text-decoration: none;
            margin: 0 10px;
        }
        footer i {
            font-size: 2em;
            margin: 0 10px;
            
        }
        @media (max-width: 768px) {
            .cards {
                flex-direction: column;
                align-items: center;
            }
        }
        {% block style %}
        .card-container {
            text-align: center;
            margin: 0 75px;
        }
        .cards {
            display: flex;
            justify-content: space-around;
            flex-wrap: wrap;
            margin:0 100px;
        }
        .card {
            background: #fff;
            border: 1px solid #ddd;
            border-radius: 8px;
            padding: 20px;
            width: 190px;
            margin: 10px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        }
        .card i{
            font-size: 3em;
        }
        .card h3 {
            font-size: 1.3em;
            margin-bottom: 10px;
        }
        .card p {
            color: #666;
        }
        {% endblock style %}
    </style>
</head>
<body>
    <nav>
        <a href="{% url "home" %}"><h3>PriceWise</h3></a>
        <div class="hamburger" onclick="toggleMenu()">
            <div></div>
            <div></div>
            <div></div>
        </div>
            <ul class="nav-links">
                <li><a href="{% url "under_construction" %}"><p>Dashboard</p></a></li>
                <li><a href="{% url 'watchlist:all_watchlists' %}"><p>Watchlist</p></a></li>
                <li><a href="{% url "under_construction" %}"><p>Notifications</p></a></li>
            {% if user.is_authenticated %}
            <li><a href="{% url "under_construction" %}"><p>{{user.username}}</p></a></li>
            <li><button onclick="location.href='{% url "accounts:logout" %}'">Logout</button></li>
            {% else %}
            <li><button onclick="location.href='{% url "accounts:login" %}'">Login</button></li>
            {% endif %}
            </ul>
        </nav>
        {% if messages %}
        <script>
            {% for message in messages %}
                alert("{{ message|escapejs }}");
            {% endfor %}
        </script>
        {% endif %}
        <div class="container">
        {% block content %}
        <header>
            <h1>Track Prices, Save Money</h1>
            <p>Monitor your favorite products across multiple stores and never miss a deal.</p>
            <div class="search-bar">
                <form action="{% url 'products:search_products' %}" method="get">
                <input type="text" placeholder="Enter product URL">
                <button type="submit">Track</button>
            </form>
            </div>
            <button onclick="location.href='{% url "tracking:send_email" %}'">Send Email</button>
            </header>
        <div class="card-container">
            <div class="cards">
                <div class="card">
                    <i class="material-symbols-outlined">text_compare</i>
                    <h3>Compare Products</h3>
                    <p>Compare prices of products across multiple stores.</p>
                </div>
                <div class="card">
                    <i class="material-symbols-outlined">eye_tracking</i>
                    <h3>Track Prices</h3>
                    <p>Track prices of your favorite products with PriceWise.</p>
                </div>
                <div class="card">
                    <i class="material-symbols-outlined">notifications_active</i>
                    <h3>Get Notified</h3>
                    <p>Get notified when prices of products drop.</p>
                </div>
            </div>
        </div>
        {% endblock content %}
        </div>
        <footer>
            <a href="#"><svg xmlns="http://www.w3.org/2000/svg" width="1.5em" height="1.5em" fill="currentColor" class="bi bi-facebook" viewBox="0 0 16 16">
                    <path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951"/>
                  </svg></a>
                <a href="#"><svg xmlns="http://www.w3.org/2000/svg" width="1.5em" height="1.5em" fill="currentColor" class="bi bi-twitter-x" viewBox="0 0 16 16">
                    <path d="M12.6.75h2.454l-5.36 6.142L16 15.25h-4.937l-3.867-5.07-4.425 5.07H.316l5.733-6.57L0 .75h5.063l3.495 4.633L12.601.75Zm-.86 13.028h1.36L4.323 2.145H2.865z"/>
                  </svg></i></a>
                <a href="#"><svg xmlns="http://www.w3.org/2000/svg" width="1.5em" height="1.5em" fill="currentColor" class="bi bi-instagram" viewBox="0 0 16 16">
                    <path d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.9 3.9 0 0 0-1.417.923A3.9 3.9 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.9 3.9 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.9 3.9 0 0 0-.923-1.417A3.9 3.9 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599s.453.546.598.92c.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.5 2.5 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.5 2.5 0 0 1-.92-.598 2.5 2.5 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233s.008-2.388.046-3.231c.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92s.546-.453.92-.598c.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92m-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217m0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334"/>
                  </svg></i></a>
            <p>
                
                <a href="#">About</a>
            </p>
        </footer>
        <script>
            function toggleMenu() {
                document.querySelector('.nav-links').classList.toggle('active');
            }
        </script>
</body>
</html>

templates/pricewise/under-construction.html
{% extends "pricewise/home.html" %}
{% block style %}
.container{
    min-height: 100vh;
    display: flex;
    align-items: center; 
    justify-content: center; 
    padding: 16px;
    background-color: white;
}
.center-text{
    text-align: center;
}
h1 .my-text-class {
    font-size: 2.25rem; /* text-4xl */
    @media (min-width: 768px) { 
      font-size: 3rem; /* md:text-5xl */
    }
    font-weight: bold; /* font-bold */
    color: black; /* text-black */
    margin-top: 2rem; /* mt-8 */
    margin-bottom: 1rem; /* mb-4 */
  }
  .my-text{
    font-size: 1.25rem; /* text-xl */
    color: #9ca3af; /* text-gray-600 */
    margin-bottom: 2rem; /* mb-8 */
    max-width: 28rem; /* max-w-md */
    margin-left: auto; /* mx-auto */
    margin-right: auto; /* mx-auto */
  }
{% endblock style %}
{% block content %}
<img src="" alt="">
<div class="center-text">
    <h1 class="my-text-class">Under Construction</h1>
    <p class="my-text">We are working on this page. Please check back later.</p>
</div>
{% endblock content %}